server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # SPA fallback — todas as rotas sem arquivo real vão para index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache de assets estáticos
    location ~* \.(css|js|png|jpg|jpeg|gif|ico|woff|woff2)$ {
        expires 1h;
        add_header Cache-Control "public";
    }
}
